In [1]:
import numpy as np

In [2]:
a_panda_numpy = np.array([100, 5, 20, 50])
a_panda_numpy

array([100,   5,  20,  50])

In [3]:
panda_family = [
    [100, 5, 20, 80], # panda mother
    [50, 2.5, 10, 40], # panda baby
    [110, 6, 22, 80], # panda father
]
family_panda_numpy = np.array(panda_family)
family_panda_numpy

array([[100. ,   5. ,  20. ,  80. ],
       [ 50. ,   2.5,  10. ,  40. ],
       [110. ,   6. ,  22. ,  80. ]])

In [4]:
family_panda_numpy[2, 0]

110.0

In [5]:
import pandas as pd


In [6]:
family_panda_df = pd.DataFrame(family_panda_numpy, 
                                index=["mother", "bayby", "father"], 
                                columns =["paws", "hair", "tail", "belly"])

In [7]:
family_panda_df

paws  hair  tail  belly
mother  100.0   5.0  20.0   80.0
bayby    50.0   2.5  10.0   40.0
father  110.0   6.0  22.0   80.0

In [8]:
family_panda_df.belly

mother    80.0
bayby     40.0
father    80.0
Name: belly, dtype: float64

In [9]:
family_panda_df.loc["father"]

paws     110.0
hair       6.0
tail      22.0
belly     80.0
Name: father, dtype: float64

In [10]:
family_panda_df.iloc[1]

paws     50.0
hair      2.5
tail     10.0
belly    40.0
Name: bayby, dtype: float64

In [11]:
family_panda_df[family_panda_df.belly==80]

paws  hair  tail  belly
mother  100.0   5.0  20.0   80.0
father  110.0   6.0  22.0   80.0

In [12]:
others_pandas = pd.DataFrame([[105, 4, 19, 80], [100, 5, 20, 80]], columns=family_panda_df.columns)

In [13]:
total_pandas = family_panda_df.append(others_pandas)
total_pandas

paws  hair  tail  belly
mother  100.0   5.0  20.0   80.0
bayby    50.0   2.5  10.0   40.0
father  110.0   6.0  22.0   80.0
0       105.0   4.0  19.0   80.0
1       100.0   5.0  20.0   80.0

In [14]:
total_pandas.drop_duplicates()

paws  hair  tail  belly
mother  100.0   5.0  20.0   80.0
bayby    50.0   2.5  10.0   40.0
father  110.0   6.0  22.0   80.0
0       105.0   4.0  19.0   80.0

In [15]:
family_panda_df["age"]=[10, 15, 5]

In [16]:
family_panda_df

paws  hair  tail  belly  age
mother  100.0   5.0  20.0   80.0   10
bayby    50.0   2.5  10.0   40.0   15
father  110.0   6.0  22.0   80.0    5

In [17]:
family_panda_df["belly"].values

array([80., 40., 80.])

In [18]:
family_panda_df["belly"]

mother    80.0
bayby     40.0
father    80.0
Name: belly, dtype: float64

In [19]:
for ind_ligne, contenu_ligne in family_panda_df.iterrows():
    print("Voici le panda %s :" % ind_ligne)
    print(contenu_ligne)
    print("--------------------")

Voici le panda mother :
paws     100.0
hair       5.0
tail      20.0
belly     80.0
age       10.0
Name: mother, dtype: float64
--------------------
Voici le panda bayby :
paws     50.0
hair      2.5
tail     10.0
belly    40.0
age      15.0
Name: bayby, dtype: float64
--------------------
Voici le panda father :
paws     110.0
hair       6.0
tail      22.0
belly     80.0
age        5.0
Name: father, dtype: float64
--------------------


In [20]:
masque = family_panda_df["belly"] == 80
pandas = family_panda_df[masque]
pandas

paws  hair  tail  belly  age
mother  100.0   5.0  20.0   80.0   10
father  110.0   6.0  22.0   80.0    5

In [21]:
masque2 = family_panda_df["belly"] == 80
pandas2 = family_panda_df[~masque2]
pandas2

paws  hair  tail  belly  age
bayby  50.0   2.5  10.0   40.0   15

In [22]:
uniques_pandas = total_pandas.drop_duplicates()
uniques_pandas

paws  hair  tail  belly
mother  100.0   5.0  20.0   80.0
bayby    50.0   2.5  10.0   40.0
father  110.0   6.0  22.0   80.0
0       105.0   4.0  19.0   80.0

In [26]:
uniques_pandas["sexe"]=["f", "f", "m", "h"] 


<ipython-input-26-ab9712416058>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  uniques_pandas["sexe"]=["f", "f", "m", "h"]


In [24]:
family_panda_df["sexe"]=["f", "f", "m"]

In [25]:
family_panda_df

paws  hair  tail  belly  age sexe
mother  100.0   5.0  20.0   80.0   10    f
bayby    50.0   2.5  10.0   40.0   15    f
father  110.0   6.0  22.0   80.0    5    m

In [27]:
# obtenir les valeurs distinctes d'une colonne :
# pour la colonne ventre, il y a deux valeurs distinctes : 40 et 80
family_panda_df.belly.unique()

array([80., 40.])