In [1]:
import numpy as np

np.random.seed(0)


In [2]:
np.array([0, 1, 2])

array([0, 1, 2])

In [3]:
np.zeros(4)

array([0., 0., 0., 0.])

In [4]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.full((4, 5), 55)

array([[55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55]])

In [6]:
x = np.full((10, 20), 4)

In [7]:
x.ndim

2

In [8]:
x.size

200

In [9]:
x.dtype

dtype('int64')

In [10]:
x[0, 1]

4

In [11]:
x

array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [12]:
x[0, 1] = 5

In [13]:
x

array([[4, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [14]:
x[0, 2] = 3.14

In [15]:
x


array([[4, 5, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [16]:
x = np.random.randint(10, size=6)

In [17]:
x

array([5, 0, 3, 3, 7, 9])

In [18]:
x[0:2]

array([5, 0])

In [19]:
x[:2]

array([5, 0])

In [20]:
x[1:3]

array([0, 3])

In [21]:
x[0:3]

array([5, 0, 3])

In [22]:
x[:3]

array([5, 0, 3])

In [23]:
x[0::3]

array([5, 3])

In [24]:
def calculate_inverse(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output

In [25]:
def calculate_inverse_two(values):
    output = np.empty(len(values))
    return [1.0/values[i] for i in range(len(values))]

In [26]:
large_table = np.random.randint(1, 10, size=1000000)

In [27]:
%timeit calculate_inverse(large_table)

3.17 s ± 1.01 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [28]:
%timeit (1.0/large_table)

2.05 ms ± 166 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [29]:
%timeit calculate_inverse_two(large_table)

2.37 s ± 245 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [30]:
test = np.array([1, 2, 4], dtype="int")

In [31]:
test = np.append(test, 45)

In [32]:
test = np.delete(test, np.argwhere(test == 2))

In [33]:
test

array([ 1,  4, 45])

In [34]:
test = np.append(test, 3.14)

In [35]:
test

array([ 1.  ,  4.  , 45.  ,  3.14])

In [36]:
test = test.astype(int)

In [37]:
test

array([ 1,  4, 45,  3])

In [38]:
# Un tableau rempli d'une séquence linéaire
# commençant à 0 et qui se termine à 20, avec un pas de 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
# Un tableau de 5 valeurs, espacées uniformément entre 0 et 1
np.linspace(0, 1, 8)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

In [40]:
x1 = np.random.randint(10, size=6)  # Tableau de dimension 1
print("nombre de dimensions de x1: ", x1.ndim)
print("forme de x1: ", x1.shape)
print("taille de x1: ", x1.size)
print("type de x1: ", x1.dtype)

print(x1)

# Pour accéder au premier élément
print(x1[0])

# Pour accéder au dernier élément
print(x1[-1])

x2 = np.random.randint(10, size=(3, 4))  # Tableau de dimension 2
print(x2[0,1])

# On peut aussi modifier les valeurs
x1[1] = "1000"
print(x1)

# Attention au type
x1[1] = 3.14
print(x1)

nombre de dimensions de x1:  1
forme de x1:  (6,)
taille de x1:  6
type de x1:  int64
[4 5 8 6 2 7]
4
7
7
[   4 1000    8    6    2    7]
[4 3 8 6 2 7]


In [48]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])


array([1, 2, 3, 3, 2, 1])

In [49]:
x = np.append(x, y)


In [53]:
print(x)

[1 2 3 3 2 1]


In [54]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [55]:
# Il y a tout d'abord des opération mathématiques simples
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # Division avec arronid

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [56]:
x = [-2, -1, 1, 2]
print("La valeur absolue: ", np.abs(x))
print("Exponentielle: ", np.exp(x))
print("Logarithme: ", np.log(np.abs(x)))

La valeur absolue:  [2 1 1 2]
Exponentielle:  [0.13533528 0.36787944 2.71828183 7.3890561 ]
Logarithme:  [0.69314718 0.         0.         0.69314718]


In [59]:
temp = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.where(temp >= 3)

(array([3, 4, 5, 6, 7, 8, 9]),)

In [60]:
np.sum(temp)

45

In [62]:
%timeit sum(large_table)


186 ms ± 57.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [63]:
%timeit np.sum(large_table)

1.6 ms ± 179 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [68]:
M = np.random.random((3, 4))
print(M)
# Notez la syntax variable.fonction au lieu de 
# np.fonction(variable). Les deux sont possibles si
# la variable est un tableau Numpy.
print("La somme de tous les éléments de M: ", M.sum())
print("Les sommes des colonnes de M: ", M.sum(axis=1))

[[0.15706731 0.19982902 0.34680143 0.84011065]
 [0.64633694 0.51997324 0.58666563 0.55643312]
 [0.66159693 0.29031213 0.32436191 0.53893595]]
La somme de tous les éléments de M:  5.668424274966976
Les sommes des colonnes de M:  [1.54380842 2.30940894 1.81520692]


In [69]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [70]:
M = np.ones((3, 3))
print("M vaut: \n", M)
print("M+a vaut: \n", M+a)

M vaut: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
M+a vaut: 
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [71]:
a = np.arange(3)
print(a)

[0 1 2]


In [72]:
# La ligne suivante crée une matrice de taille 3x1
# avec trois lignes et une colonne.
b = np.arange(3)[:, np.newaxis]
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])